import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { dehydrate, QueryClient } from "react-query";
import { useName } from "../src/api/alan";
import { getName } from "../src/api/alan/methods";
import { queryKey } from "../src/api/key";
import { queryOptions } from "../src/api/queryClient";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { name } = useName();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>{name}</main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const queryClient = new QueryClient(queryOptions);

  await queryClient.prefetchQuery([queryKey.ALAN], () => getName());

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default Home;
